[global]
disable = ["MD013", "MD028"]

[per-file-ignores]
"docs/**/*.md" = ["MD012", "MD022"]

[MD024]
siblings-only = true

[MD033]
allowed-elements = ["a", "br", "details", "summary", "sub", "sup"]

[MD052]
shortcut-syntax = true
